'use server';

/**
 * @fileOverview An AI strategy mentor, NIKO, that provides tailored strategies based on business data.
 *
 * - getNikoStrategy - A function that handles the strategy generation process.
 * - NikoStrategyInput - The input type for the getNikoStrategy function.
 * - NikoStrategyOutput - The return type for the getNikoStrategy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const NikoStrategyInputSchema = z.object({
  businessData: z
    .string()
    .describe(
      'Comprehensive business data, including but not limited to current operations, performance metrics, and scaling challenges.'
    ),
});
export type NikoStrategyInput = z.infer<typeof NikoStrategyInputSchema>;

const NikoStrategyOutputSchema = z.object({
  strategy: z
    .string()
    .describe(
      'A tailored business strategy generated by NIKO, providing actionable insights and recommendations for scaling operations effectively.'
    ),
});
export type NikoStrategyOutput = z.infer<typeof NikoStrategyOutputSchema>;

export async function getNikoStrategy(input: NikoStrategyInput): Promise<NikoStrategyOutput> {
  return nikoStrategyFlow(input);
}

const nikoStrategyPrompt = ai.definePrompt({
  name: 'nikoStrategyPrompt',
  input: {schema: NikoStrategyInputSchema},
  output: {schema: NikoStrategyOutputSchema},
  prompt: `You are NIKO, an AI strategic mentor for businesses. Analyze the provided business data and generate a tailored strategy with actionable insights for scaling operations effectively.

Business Data: {{{businessData}}}

Provide a concise and actionable strategy.
`,
});

const nikoStrategyFlow = ai.defineFlow(
  {
    name: 'nikoStrategyFlow',
    inputSchema: NikoStrategyInputSchema,
    outputSchema: NikoStrategyOutputSchema,
  },
  async input => {
    const {output} = await nikoStrategyPrompt(input);
    return output!;
  }
);
